hw02: main.cpp doprava.cpp
	g++ -pedantic -Wall -Werror -std=c++17 -g /home/vojtechh/Documents/ppc/homeworks/hw02/main.cpp /home/vojtechh/Documents/ppc/homeworks/hw02/doprava.cpp -o /home/vojtechh/Documents/ppc/homeworks/hw02/hw02
clean: rm hw02 