######################################################################
# Automatically generated by qmake (3.1) Sun Jun 20 12:18:43 2021
######################################################################

TEMPLATE = app
TARGET = BigRedButton
QT += widgets core
INCLUDEPATH += .


# Input
HEADERS += GPIO.h tlacitko.h
SOURCES += GPIO.cpp main.cpp
